package alexp.blog.mybatisModel;

public class PostWithBLOBs extends Post {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.fullPostText
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    private String fullposttext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.shortTextPart
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    private String shorttextpart;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.fullPostText
     *
     * @return the value of posts.fullPostText
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    public String getFullposttext() {
        return fullposttext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.fullPostText
     *
     * @param fullposttext the value for posts.fullPostText
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    public void setFullposttext(String fullposttext) {
        this.fullposttext = fullposttext == null ? null : fullposttext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.shortTextPart
     *
     * @return the value of posts.shortTextPart
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    public String getShorttextpart() {
        return shorttextpart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.shortTextPart
     *
     * @param shorttextpart the value for posts.shortTextPart
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    public void setShorttextpart(String shorttextpart) {
        this.shorttextpart = shorttextpart == null ? null : shorttextpart.trim();
    }
}