package alexp.blog.mybatisModel;

public class Tag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.Id
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.name
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.Id
     *
     * @return the value of tags.Id
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.Id
     *
     * @param id the value for tags.Id
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.name
     *
     * @return the value of tags.name
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.name
     *
     * @param name the value for tags.name
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}