package alexp.blog.mybatisDao.auto;

import alexp.blog.mybatisModel.CommentRating;
import alexp.blog.mybatisModel.CommentRatingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentRatingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_ratings
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    long countByExample(CommentRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_ratings
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    int deleteByExample(CommentRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_ratings
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_ratings
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    int insert(CommentRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_ratings
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    int insertSelective(CommentRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_ratings
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    List<CommentRating> selectByExample(CommentRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_ratings
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    CommentRating selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_ratings
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") CommentRating record, @Param("example") CommentRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_ratings
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    int updateByExample(@Param("record") CommentRating record, @Param("example") CommentRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_ratings
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    int updateByPrimaryKeySelective(CommentRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_ratings
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    int updateByPrimaryKey(CommentRating record);
}