package alexp.blog.mybatisDao.auto;

import alexp.blog.mybatisModel.PostsTags;
import alexp.blog.mybatisModel.PostsTagsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PostsTagsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_tags
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    long countByExample(PostsTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_tags
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    int deleteByExample(PostsTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_tags
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    int insert(PostsTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_tags
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    int insertSelective(PostsTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_tags
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    List<PostsTags> selectByExample(PostsTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_tags
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") PostsTags record, @Param("example") PostsTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_tags
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    int updateByExample(@Param("record") PostsTags record, @Param("example") PostsTagsExample example);
}