package alexp.blog.mybatisDao.auto;

import alexp.blog.mybatisModel.PostRating;
import alexp.blog.mybatisModel.PostRatingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PostRatingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_ratings
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    long countByExample(PostRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_ratings
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    int deleteByExample(PostRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_ratings
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_ratings
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    int insert(PostRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_ratings
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    int insertSelective(PostRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_ratings
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    List<PostRating> selectByExample(PostRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_ratings
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    PostRating selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_ratings
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") PostRating record, @Param("example") PostRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_ratings
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    int updateByExample(@Param("record") PostRating record, @Param("example") PostRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_ratings
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    int updateByPrimaryKeySelective(PostRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_ratings
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    int updateByPrimaryKey(PostRating record);
}