package alexp.blog.mybatisDao.auto;

import alexp.blog.mybatisModel.UsersRoles;
import alexp.blog.mybatisModel.UsersRolesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsersRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_roles
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    long countByExample(UsersRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_roles
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    int deleteByExample(UsersRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_roles
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    int insert(UsersRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_roles
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    int insertSelective(UsersRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_roles
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    List<UsersRoles> selectByExample(UsersRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_roles
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") UsersRoles record, @Param("example") UsersRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_roles
     *
     * @mbg.generated Sun May 20 22:57:41 CST 2018
     */
    int updateByExample(@Param("record") UsersRoles record, @Param("example") UsersRolesExample example);
}