/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Dec 04 13:53:54 GMT 2018
 */

package alexp.blog.service;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class PostServiceImpl_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "alexp.blog.service.PostServiceImpl"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/_c/j72s8y7x1cld6t7mvpvtxtnh0000gn/T/"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "/Users/hengjiechen/Develop/Java/JavaSpringMvcBlog"); 
    java.lang.System.setProperty("user.home", "/Users/hengjiechen"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "hengjiechen"); 
    java.lang.System.setProperty("user.timezone", "Asia/Shanghai"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(PostServiceImpl_ESTest_scaffolding.class.getClassLoader() ,
      "org.springframework.data.repository.query.Param",
      "org.springframework.data.jpa.repository.Query",
      "alexp.blog.repository.PostRepository",
      "org.springframework.security.core.userdetails.UsernameNotFoundException",
      "alexp.blog.service.PostService",
      "alexp.blog.model.User",
      "org.springframework.security.core.userdetails.UserDetailsService",
      "org.springframework.beans.factory.annotation.Autowired",
      "org.springframework.data.domain.AbstractPageRequest",
      "org.springframework.data.repository.CrudRepository",
      "org.springframework.data.annotation.QueryAnnotation",
      "org.springframework.data.domain.Sort$Direction",
      "alexp.blog.model.Post",
      "alexp.blog.model.Comment",
      "alexp.blog.service.AuthException",
      "alexp.blog.model.PostRating",
      "org.springframework.stereotype.Service",
      "org.springframework.data.repository.Repository",
      "alexp.blog.service.UploadedAvatarInfo",
      "org.springframework.security.core.userdetails.UserDetails",
      "org.springframework.data.domain.Pageable",
      "org.springframework.data.domain.Sort",
      "org.springframework.security.core.AuthenticationException",
      "org.springframework.core.convert.converter.Converter",
      "org.springframework.data.repository.PagingAndSortingRepository",
      "alexp.blog.service.UserService",
      "alexp.blog.model.Tag",
      "org.springframework.data.domain.PageRequest",
      "alexp.blog.model.PostEditDto",
      "org.springframework.data.domain.Page",
      "org.springframework.data.domain.Sort$Order",
      "alexp.blog.model.Rating",
      "org.springframework.data.domain.Slice",
      "alexp.blog.model.Role",
      "org.springframework.data.domain.Sort$NullHandling",
      "org.springframework.stereotype.Component",
      "alexp.blog.repository.TagRepository",
      "alexp.blog.service.PostServiceImpl",
      "alexp.blog.repository.PostRatingRepository",
      "alexp.blog.service.AlreadyVotedException",
      "org.springframework.data.jpa.repository.JpaRepository",
      "org.springframework.util.StringUtils"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("alexp.blog.model.Post", false, PostServiceImpl_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("alexp.blog.model.PostRating", false, PostServiceImpl_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("alexp.blog.model.User", false, PostServiceImpl_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("alexp.blog.repository.PostRatingRepository", false, PostServiceImpl_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("alexp.blog.repository.PostRepository", false, PostServiceImpl_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("alexp.blog.repository.TagRepository", false, PostServiceImpl_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("alexp.blog.service.UserService", false, PostServiceImpl_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(PostServiceImpl_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "alexp.blog.service.PostServiceImpl",
      "org.springframework.data.domain.Sort$Direction",
      "org.springframework.data.domain.AbstractPageRequest",
      "org.springframework.data.domain.PageRequest",
      "org.springframework.data.domain.Sort",
      "org.springframework.data.domain.Sort$Order",
      "org.springframework.util.StringUtils",
      "org.springframework.data.domain.Sort$NullHandling",
      "alexp.blog.model.Post",
      "alexp.blog.model.PostEditDto",
      "alexp.blog.model.User",
      "alexp.blog.model.Rating",
      "alexp.blog.model.PostRating",
      "alexp.blog.service.AlreadyVotedException"
    );
  }
}
